-- AlterTable
ALTER TABLE "Page" ADD COLUMN     "userId" TEXT NOT NULL DEFAULT '0ce36a76-0b5b-4a27-94c4-48b402205b85';

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
